### PR TITLE
Other bug fixes

### PR DESCRIPTION
**Pull request by arti-karnik**
- show default weather when user deny location permission
- Favoite/non favorite show in list
- Bug fixes found during unit testing
- Added missing cities 
-

### CODE REVIEW

**Review by JoeDonMalone — CHANGES_REQUESTED** [review]
Arti, please save your list.js changes locally and then commit once you pull my latest changes.

**Review by brodie80 — APPROVED** [review]

**Review by brodie80 — APPROVED** [review]

**Review by brodie80 — APPROVED** [review]

**Comment by brodie80** [comment]
I'm showing conflicts on this one. Going to try and fix then merge

**Comment by arti-karnik** [comment]
conflicts resolved

**Comment by arti-karnik** [comment]
please merge this to main branch

**Review by JoeDonMalone — APPROVED** [review]

**Pull request merged**
